-- Found ament_cmake: 0.9.7 (/home/vlad/ros2_foxy/install/ament_cmake/share/ament_cmake/cmake)
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found rosidl_default_generators: 1.0.0 (/home/vlad/ros2_foxy/install/rosidl_default_generators/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_introspection_c;rosidl_typesupport_fastrtps_c
-- Found rosidl_adapter: 1.1.0 (/home/vlad/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake)
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_introspection_cpp;rosidl_typesupport_fastrtps_cpp
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.5") 
CMake Error at /home/vlad/ros2_foxy/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  pose_interface --arguments-file
  /home/vlad/ros2_ws/src/build/pose_interface/rosidl_adapter__arguments__pose_interface.json
  --output-dir
  /home/vlad/ros2_ws/src/build/pose_interface/rosidl_adapter/pose_interface
  --output-file
  /home/vlad/ros2_ws/src/build/pose_interface/rosidl_adapter/pose_interface.idls)
  returned error code 1:

  Error with: pose_interface GetPose_Response Persons

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/vlad/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/vlad/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/vlad/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
      return convert_srv_to_idl(
    File "/home/vlad/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
      srv = parse_service_string(package_name, input_file.stem, content)
    File "/home/vlad/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 846, in parse_service_string
      response_message = parse_message_string(
    File "/home/vlad/ros2_foxy/install/rosidl_adapter/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 503, in parse_message_string
      raise InvalidFieldDefinition(line)

  rosidl_adapter.parser.InvalidFieldDefinition: Persons

Call Stack (most recent call first):
  /home/vlad/ros2_foxy/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:25 (rosidl_generate_interfaces)


-- Configuring incomplete, errors occurred!
See also "/home/vlad/ros2_ws/src/build/pose_interface/CMakeFiles/CMakeOutput.log".
